### ISSUE TITLE
Jellyfin

### ISSUE THREAD

**Issue by nelsongraca** [LITUATUI/M3UPT#52]
I have tried adding the m3u and epg to jellyfin, channels are detected from m3u none plays, epg nothing seems to work.

Is it possible to use?

**Comment by LITUATUI** [comment]
Sorry but I don't use Jellyfin. Have you tried other playlists on it?

**Comment by tiagogaspar8** [comment]
Hey @LITUATUI,

I do have Jellyfin and I'd love to get this working there.
I added both m3u and the epg to jellyfin. m3u works, but the epg seems to be the one giving issues, these are the errors I get:
```
--------------------------It loads all channels previous to thses entries---------------------------
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Rádio Sines"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Fama Rádio"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Rádio Terra Nova"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Rádio Universitária de Coimbra"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Rádio Universitária do Minho"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Rádio Vale do Minho"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Rádio Quântica"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Rádio Zero"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Venice Classic Radio - Auditorium"
[2024-11-24 19:27:54.534 +00:00] [INF] [31] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Parsed channel: "Venice Classic Radio - Live"
[2024-11-24 19:27:54.564 +00:00] [INF] [31] Jellyfin.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "https://m3upt.com/epg"
[2024-11-24 19:27:54.564 +00:00] [INF] [31] Jellyfin.LiveTv.Listings.XmlTvListingsProvider: Downloading xmltv listings from "https://m3upt.com/epg"
[2024-11-24 19:27:55.149 +00:00] [ERR] [29] Jellyfin.LiveTv.Listings.ListingsManager: Error adding metadata
System.Xml.XmlException: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.ReadToDescendant(String name)
   at Jellyfin.XmlTv.XmlTvReader.GetChannels()
   at Jellyfin.LiveTv.Listings.XmlTvListingsProvider.GetChannels(ListingsProviderInfo info, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Listings.ListingsManager.GetEpgChannels(IListingsProvider provider, ListingsProviderInfo info, Boolean enableCache, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Listings.ListingsManager.AddMetadata(IListingsProvider provider, ListingsProviderInfo info, IEnumerable`1 tunerChannels, Boolean enableCache, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.Listings.ListingsManager.AddProviderMetadata(IList`1 channels, Boolean enableCache, CancellationToken cancellationToken)
--------------------------This error repeats for all channels in the m3u---------------------------
```
Any suggestions of why this might be happening?

If you want me to test something out let me know.

Relevant docs:
https://jellyfin.org/docs/general/server/live-tv/setup-guide#adding-guide-data

**Comment by tiagogaspar8** [comment]
Update, it seems that this is related to the fact that Jellyfin only supports xml files and the epg is currently in xml.gz, would it be an option to have an xml version for jellyfin?

**Comment by LITUATUI** [comment]
Uncompressed EPG XML files are too big for Cloudflare Pages (25 MB is the maximum file size).

I use Jellyfin to watch my media collection, but for IPTV the experience is awful.

**Comment by tiagogaspar8** [comment]
Sorry for the delay.
How does Cloudflare Pages impact this? Cloudflare Pages doesn't actually serve files, it redirects the connection to the github repo, so you're actually downloading the file from Github.
Nevertheless i would just want a change that allows the xml to be present in the github repo, maybe changing this line here:
https://github.com/LITUATUI/M3UPT/blob/main/EPG/epg-pt.sh#L37
Maybe this would suffice allowing the .xml files to be present alongside the compressed one, this should't affect current functionality and allow use with Jellyfin.
Hopefully this makes sense!

**Comment by LITUATUI** [comment]
Sorry, you're correct. I was tired and forgot this was the public repo, not the private repo that is used by Cloudflare Pages to build the website.

However, with big XML files the .git folder will get massive very fast, it's already 7 GB...

You can use a simple bash script to download and extract the compressed XML.

**Comment by tiagogaspar8** [comment]
Wouldn't it be possible to have a single .xml moved to the epg folder? For example, right now the epg link directs to the MEO epg, so that's the one that can be left outside of the archive, since it has about 6MB it should be fine (beside the archived one, I wouldn't want to change current behavior).
I tried to understand the scripting that's running in actions to submit a pull request but I couldn't understand it.
If you have some pointers for me to research I can try to contribute and open a pull reuqest with this.
